services:
  webapi:
    image: ogavrylenko/webapi-sample:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development